
services:
  db:
    container_name: vector_db
    image: pgvector/pgvector:pg17
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${VECTOR_DB_NAME:-vector_dev}
      - POSTGRES_USER=${POSTGRES_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD:-postgres}
    ports:
      - "${VECTOR_HOST_PORT:-5434}:5432"  # Host:Container
    restart: always

volumes:
  postgres_data_dev:
  redis_data_dev:
