# START OF pyproject.toml
[project]
name = "sirr-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "celery>=5.5.3",
  "django>=5.2.6",
  "django-cors-headers>=4.9.0",
  "django-filter>=25.1",
  "django-redis>=6.0.0",
  "djangorestframework>=3.16.1",
  "djangorestframework-simplejwt>=5.5.1",
  "psycopg[binary]>=3.2.10",
  "redis[hiredis]>=6.4.0",
  "pynacl>=1.6.0",
  "dspy>=3.0.3",
  "litellm==1.77.1",
  "django-pwnedpasswords-validator>=1.0.1",
  "django-pwned-passwords>=4.1.0",
  "argon2-cffi>=25.1.0",
  "bcrypt>=4.3.0",
  "pyotp>=2.9.0",
  "litellm==1.77.1"
]
[dependency-groups]
dev = [
  "datasets>=4.1.1",
  "django-diagram>=0.0.1",
  "django-stubs>=5.2.2",
  "djangorestframework-stubs>=3.16.2",
  "mypy>=1.17.1",
  "pandas>=2.3.2",
  "poethepoet>=0.37.0",
  "ruff>=0.12.12",
]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true
pretty = true
warn_no_return = true
follow_imports_for_stubs = true
plugins = [
  "mypy_django_plugin.main",
  "mypy_drf_plugin.main",
]

[[tool.mypy.overrides]]
# Django migrations should not produce any errors:
module = "*.migrations.*"
ignore_errors = true
[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
  "migrations",
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.13
target-version = "py313"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F", "I"]
ignore = ["E722"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
case-sensitive = true

[tool.django-stubs]
django_settings_module = "core.settings"

[tool.poe.tasks]
build = { cmd = "docker compose -f ../docker-compose.yml build ", help = "Build/rebuild the docker container." }
dev = { cmd = "docker compose -f ../docker-compose.yml up", help = "Run the development server." }
devlm = { cmd = "docker compose -f ../docker-compose.yml --profile lm up", help = "Run the development server with Ollama." }
makemigrations = { cmd = "docker compose -f ../docker-compose.yml run --rm sirr_api python manage.py makemigrations --settings=core.settings", help = "Generate new database migrations." }
migrate = { cmd = "docker compose -f ../docker-compose.yml run --rm sirr_api python manage.py migrate --settings=core.settings", help = "Apply database migrations." }
shell = { cmd = "docker compose -f ../docker-compose.yml exec sirr_api python manage.py shell --settings=core.settings", help = "Open Django interactive shell." }
down = { cmd = "docker compose -f ../docker-compose.yml --profile lm down --remove-orphans", help = "Stop and remove containers, networks, images, and volumes." }
# Only run this if you want to drop the database and start from scratch.
clean = { cmd = "docker compose -f ../docker-compose.yml --profile lm down --remove-orphans -v", help = "Docker down and dropping volumes/database" }
createsuperuser = { cmd = "docker compose -f ../docker-compose.yml exec sirr_api python manage.py createsuperuser --settings=core.settings", help = "Create a Django superuser inside the API container." }
create_test_admin = { cmd = "docker compose -f ../docker-compose.yml exec sirr_api python manage.py create_admin_with_keys", help = "Automated creation of an admin with a new keypair." }
create_test_caseworker = { cmd = "docker compose -f ../docker-compose.yml exec sirr_api python manage.py create_test_caseworker", help = "Automated creation of a caseworker with a new keypair." }
create_investigator_invitation = { cmd = "docker compose -f ../docker-compose.yml exec sirr_api python manage.py create_investigator_invitation", help = "Creates an inactive investigator and generates an onboarding invitation." }

[tool.poe.tasks.startapp]
help = "Create a new Django app under apps/<app> using Docker"
shell = """
    docker compose -f ../docker-compose.yml run --rm --no-TTY sirr_api sh -c "
  mkdir -p apps/${app} &&
  python manage.py startapp ${app} apps/${app} --settings=core.settings &&
  chown -R --reference=apps apps/${app}
"
"""
args = [
  { name = "app", help = "The Django app name to create", positional = true }
]
