# Generated by Django 5.2.6 on 2025-09-25 01:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_caseworker_user_public_key_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_complete',
            field=models.BooleanField(default=False, help_text='Indicates if the user has completed the initial onboarding and TOTP setup.', verbose_name='Onboarding Complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Encrypted TOTP secret key.', max_length=255, verbose_name='TOTP Secret'),
        ),
        migrations.CreateModel(
            name='OnboardingInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The single-use token for the onboarding URL.', unique=True, verbose_name='Invitation Token')),
                ('expires_at', models.DateTimeField(help_text='The timestamp when this invitation link expires.', verbose_name='Expires At')),
                ('used_at', models.DateTimeField(blank=True, help_text='The timestamp when the token was successfully used.', null=True, verbose_name='Used At')),
                ('user', models.OneToOneField(help_text='The inactive user this invitation is for.', on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Invitation',
                'verbose_name_plural': 'Onboarding Invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
