# Generated by Django 5.2.6 on 2025-09-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_onboarding_complete_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginvitation',
            name='token',
            field=models.CharField(editable=False, help_text='The single-use, URL-safe token for the onboarding link.', max_length=64, unique=True, verbose_name='Invitation Token'),
        ),
    ]
