# Generated by Django 5.2.6 on 2025-09-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
        ('users', '0005_alter_onboardinginvitation_token'),
    ]

    operations = [
    ]
