# Generated by Django 5.2.6 on 2025-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_onboardinginvitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Counter for failed login attempts. Resets on successful login.', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Designates if the account is locked due to too many failed login attempts.', verbose_name='Is Locked'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_totp_timestamp',
            field=models.BigIntegerField(blank=True, help_text="The Unix timestamp of the last successfully used TOTP code's time window, to prevent replay attacks.", null=True, verbose_name='Last TOTP Timestamp'),
        ),
    ]
