# Generated by Django 5.2.6 on 2025-09-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250926_0235'),
        ('users', '0007_alter_user_email'),
    ]

    operations = [
    ]
