# Generated by Django 5.2.6 on 2025-09-20 17:11

import apps.reports.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.AddField(
            model_name='attachment',
            name='key_envelope',
            field=models.JSONField(blank=True, help_text='The encrypted attachment key (K_attach_i).', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='nonce',
            field=models.BinaryField(blank=True, help_text="The unique nonce for the attachment's encryption.", null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='associated_data',
            field=models.JSONField(default=dict, help_text='Non-secret, integrity-protected metadata (e.g., report type, coarse timestamp).'),
        ),
        migrations.AddField(
            model_name='report',
            name='body_nonce',
            field=models.BinaryField(blank=True, help_text='The 24-byte XChaCha20 nonce used for encrypting the report body.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='encrypted_body',
            field=models.BinaryField(blank=True, help_text='The raw ciphertext of the report.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='key_envelope',
            field=models.JSONField(blank=True, help_text="The encrypted report key (K_report) and the reporter's ephemeral public key.", null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='checksum',
            field=models.CharField(blank=True, help_text='The SHA-256 hash of the encrypted file content (ciphertext).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(help_text='The encrypted file content (ciphertext).', upload_to=apps.reports.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov'])]),
        ),
    ]
