# Generated by Django 5.2.6 on 2025-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_data_attachment_key_envelope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportassignment',
            name='key_envelope',
            field=models.JSONField(blank=True, help_text='The re-encrypted report key (K_report) for the assigned investigator.', null=True),
        ),
    ]
