# Generated by Django 5.2.6 on 2025-09-21 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportassignment_key_envelope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportassignment',
            index=models.Index(fields=['assignee'], name='reports_rep_assigne_388746_idx'),
        ),
    ]
