# Generated by Django 5.2.6 on 2025-09-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportassignment_reports_rep_assigne_388746_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='analysis_data',
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='spam_reasoning',
            field=models.TextField(blank=True, help_text='The reasoning behind the spam prediction.'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='The urgency of the report for criminal investigation.', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='urgency_reasoning',
            field=models.TextField(blank=True, help_text='The reasoning behind the urgency prediction.'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Whether the report is spam.'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='model_version',
            field=models.CharField(default='v1', max_length=10),
        ),
    ]
