# Generated by Django 5.2.6 on 2025-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_aianalysis_analysis_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='The urgency of the report for criminal investigation.', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
    ]
