# Generated by Django 5.2.6 on 2025-09-28 12:00

from django.db import migrations, models

def populate_report_numbers(apps, schema_editor):
    """
    Populates the new `report_number` field for existing Report objects
    before the unique constraint is applied.
    """
    Report = apps.get_model('reports', 'Report')
    for report in Report.objects.all():
        # Generate a unique report number based on the existing UUID
        report.report_number = f"CASE-{str(report.id).split('-')[0].upper()}"
        report.save(update_fields=['report_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_aianalysis_urgency_alter_report_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened'), ('closed', 'Closed')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='report_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.RunPython(populate_report_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='report',
            name='report_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]