# Generated by Django 5.2.6 on 2025-09-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_important_report_label_report_report_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_number',
        ),
    ]
