# Generated by Django 5.2.6 on 2025-11-01 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def reporter_note_attachment_upload_path(instance, filename):
    """Generate upload path for reporter note attachments: reporter_notes/{report_id}/{filename}"""
    return f"reporter_notes/{instance.report.id}/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_assigned_at_report_closed_at_report_opened_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text="The content of the reporter's note.")),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment for the note.', null=True, upload_to=reporter_note_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_notes', to='reports.report')),
            ],
            options={
                'verbose_name': 'Reporter Note',
                'verbose_name_plural': 'Reporter Notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', '-created_at'], name='reports_rep_report__8a4f2b_idx')],
            },
        ),
    ]

